1. What does one need to do to use a module?
In order to utilize a module, the user must import that respective module with the appropriate resources the user is needing to reference such as: import Numpy or import Math.

2. Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.

In [3]:
# 2. CONTINUED
import numpy as np 
a = np.array([1, 3 , 2])
print(a)
# this is a vector with three rows and two columns

[1 3 2]


3. What is a benefit of using Exception handling?
Rather than run a command that results in an error message, one can input an exception block that can allow the user to run past the error. 

4. NumPy arrays are like what Python data type?
Arrays sharing a commonality with lists.
They are both mutable and can store multiple elements; however, arrays can store only the same data type whereas a list can store various data types together.

5. What is one of the main benefits of using NumPy arrays.
NumPy arrays can store a large amount of data without taking more data storage. Arrays can also be used to reference algorithms or codes alleviating the mundane repititiveness of typing the same code over and over. 

6. What is one of the main requirements about the 'dtype' of NumPy arrays?
dtypes can only be used within NumPy due to its vast array of numerical coding references it has compared to python. 

7. Of the 10 uses of NumPy, name 2.
    1. Utilization of arrays and the ability to create and condensce your own developed coding.
    2. The modules in which a user can store such arrays within. There is utility in referencing modules due to its already established vast library or codes.

8. Name one of the other libraries we'll use with NumPy?
A common library that will be used as a data analyst is the Math module. 

9. What is the shape of NumPy arrays?
The shape refers to the number of elements within a dimension which can stack to create a 3-dimensional figure or can be miniscule resulting in a vector or a single dimensional block.

10. What is a Tensor?
A tensor depicts a dimension with three or more axises.

11. Name a reason why it's better using  NumPy for Data Analysis than using a Python List?
NumPy is faster which allows for more conveniency in its utility. NumPy also uses less memory space than Python list may. 

12. When creating an "empty" array, where do the elements come from?
An element within an array are either derived from another module or created by the user. The compilation of elements within an array are all of the same type such as strings, integers, or floats. 


In [1]:
# 13. DateTime 
import datetime as d 
meow = d.datetime.now()
meow

datetime.datetime(2023, 2, 17, 9, 25, 7, 799600)

In [15]:
# 14. Printing the full month name
print(meow.strftime("%B\n"))

February



In [22]:
# 15. 
def greet(first_name, day="Friday"):
    print(f"Hey {first_name}, Happy {day}.")
greet('Ricardo', 'Friday')
greet('Johan')

Hey Ricardo, Happy Friday.
Hey Johan, Happy Friday.


In [29]:
# 16. Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). You can use the reshape method -- `.reshape()`
import numpy as n
bot = n.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])

# Reshaping the array to have shape (2, 3, 2)
reshaped_bots = bot.reshape((2, 3, 2))

print(reshaped_bots)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [35]:
# 17. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20
import numpy as n 

sox = n.linspace(0, 20, 6)
print(sox)

# 18. 5. Make a Deep Copy of the above array you created.
joe = n.copy(sox)
print(joe)

[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]


19. What are 2 reasons we use NumPy arrays over Python Lists
NumPy arrays are faster and easier to reference with various data types condensced. 
NumPy arrays take up less memory space than a list requires. 