1. What does Pandas stand for?
 - Pandas is derived from the phrase 'Panel Data' which refers to a python package used to analyze data.

2. What are the 2 collections used in Pandas?
 - Two collections used within Pandas is 'Series' and 'DataFrame'.

3. Name 4 things Pandas can do for us.
 - data cleaning, normalization, visualization, and inspections

4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
 - 
5. What is a CSV
 - CSV files can be deemed as storages for big data sets that can be referred towards. 
6. When cleaning data what values do we not like in our data?
 - Zero, null and corrupted data are values that should be addressed within any addressed datasets.

### **1. Concatenate these 3 arrays into a new array named 'newArray'...**

In [2]:
Arr1 = ([[25, 16]]) 
Arr2 = ([[11, 2], [13, 4]]),
Arr3 = ([[7, 81], [5, 6], [11, 12]])

concatenate_newArray = Arr1, Arr2, Arr3
print(concatenate_newArray) 

([[25, 16]], ([[11, 2], [13, 4]],), [[7, 81], [5, 6], [11, 12]])


### **2. Sort 'newArray' in order into 'sorted Array'**

In [36]:
Arr1 = [[25, 16]] 
Arr2 = [[11, 2], [13, 4]]
Arr3 = [[7, 81], [5, 6], [11, 12]]

newArray = Arr1 + Arr2 + Arr3
sorted(newArray)

[[5, 6], [7, 81], [11, 2], [11, 12], [13, 4], [25, 16]]

### **3. Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.** ###

In [38]:
import numpy as np

Arr1 = [[25, 16]] 
Arr2 = [[11, 2], [13, 4]]
Arr3 = [[7, 81], [5, 6], [11, 12]]

newArray = Arr1 + Arr2 + Arr3
sortedArray = sorted(newArray)
reshapedArray = np.reshape(sortedArray,(2,2,3))
print(reshapedArray)

[[[ 5  6  7]
  [81 11  2]]

 [[11 12 13]
  [ 4 25 16]]]


### **4. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.**

In [28]:
#seperate into two groups
(alpha, bravo)  = reshapedArray

(alpha_sub1, alpha_sub2) = alpha #break subgroup 1
print(alpha_sub1)
print(alpha_sub2)

(bravo_sub1, bravo_sub2) = bravo #break subgroup 2
print(bravo_sub1)
print(bravo_sub2)

[5 6 7]
[81 11  2]
[11 12 13]
[ 4 25 16]


### **5. Combine and sort the following arrays into one called 'comboArray' ...**

In [68]:
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = (one, two, three)

print(sorted(comboArray))

[[0, 1, 2, 3, 4, 5, 6, 7], [10, 11, 12, 13, 14, 15, 16, 17], [20, 21, 22, 23, 24, 25, 26, 27]]


### **6. Take 'comboArray' and perform the following slicing activities:**

In [6]:
import numpy as np
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = (one, two, three)

a, b, c = sorted(comboArray) 
new = np.concatenate((a, b, c), axis=None)
print(new)



sec1 = new[2] # the second element
print(sec1)

sec2 = new[3:]  #all elements from the 3rd element to the last
print(sec2)


sec3 = new[4:16]  #all elements from the 4th to the 14th elements
print(sec3)

sec4 = new[18:]  #the last 6 elements
print(sec4)

sec5 = new[-15:-1]  # all element from #0 up to and including #15, 
                   # using the negative number method, i.e. taking a section 
                   # from the end.
print(sec5)

sec6 = new[20:24:2]
print(sec6)  

sec7 = new[-24:-1:5]
print(sec7)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
2
[ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 4  5  6  7 10 11 12 13 14 15 16 17]
[22 23 24 25 26 27]
[11 12 13 14 15 16 17 20 21 22 23 24 25 26]
[24 26]
[ 0  5 12 17 24]


### **7. Using simple math operations, broadcast the addition `(+)`, division `(/)`, and multiplication `(*)` operations for these 2 arrays**

In [27]:
import numpy as np

star = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

planet = np.array([[17.0, 70.0, 10.7]])

star+planet

array([[[ 17.  ,  70.  ,  10.8 ],
        [ 27.  ,  80.3 ,  20.71]],

       [[ 37.  ,  90.02,  30.8 ],
        [ 47.  , 101.  ,  41.  ]],

       [[ 57.4 ,  94.  ,  50.7 ],
        [ 32.  ,  85.5 ,  36.2 ]]])

### **7. Continued**

In [28]:
star*planet

array([[[0.00000e+00, 0.00000e+00, 1.07000e+00],
        [1.70000e+02, 7.21000e+02, 1.07107e+02]],

       [[3.40000e+02, 1.40140e+03, 2.15070e+02],
        [5.10000e+02, 2.17000e+03, 3.24210e+02]],

       [[6.86800e+02, 1.68000e+03, 4.28000e+02],
        [2.55000e+02, 1.08500e+03, 2.72850e+02]]])

### **7. Continued**

In [29]:
star//planet

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 0., 1.],
        [1., 0., 2.]],

       [[2., 0., 3.],
        [0., 0., 2.]]])

### **8. Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont**

In [30]:
star-planet

array([[[-17.  , -70.  , -10.6 ],
        [ -7.  , -59.7 ,  -0.69]],

       [[  3.  , -49.98,   9.4 ],
        [ 13.  , -39.  ,  19.6 ]],

       [[ 23.4 , -46.  ,  29.3 ],
        [ -2.  , -54.5 ,  14.8 ]]])

### **9. Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.**

In [86]:
print(star[star % 3 ==0])
print(planet[planet % 3 == 0])

[ 0.  0. 30. 24. 15.]
[]


### **10. Using `Series`, create a `DataFrame` that looks like this:**

In [39]:
import pandas as pd

Ingredients = ['Flour', 'Milk', 'Eggs', 'Spam']
Quantity = [4, 1, 2, 1]
Unit = ['cups', 'cup', 'large', 'can']

# creating the needed series
Ingredients_series = pd.Series(Ingredients)
Quantity_series = pd.Series(Quantity)
Unit_series = pd.Series(Unit)

#establishing the dictionary
frame = {'Ingredients': Ingredients_series, 'Quantity': Quantity_series, 'Unit': Unit_series}

# Creating the dataframe
output = pd.DataFrame(frame)
print(output)
print('Name:   Dinner,     dtype: object')

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can
Name:   Dinner,     dtype: object


### **11. Take this data and create a DataFrame named studentData**

In [44]:
print("Title: studentdata \n")

import pandas as pd
Name = ['Jai', 'Janusha', 'Gaurav', 'Anuj']
Height = [5.1, 6.2, 5.1, 5.2]
Qualifications = ['Msc', 'MA', 'Msc', 'Msc']
Address = ['Delhi', 'Doha', 'Chennai', 'Dakhar']
Age = [21, 23, 24, 21]
Pets = ['Dog', 'Bunny', 'Chinchilla', 'Parrot']
Sports = ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']

Name_series = pd.Series(Name)
Height_series = pd.Series(Height)
Qualifications_series = pd.Series(Qualifications)
Address_series = pd.Series(Address)
Age_series = pd.Series(Age)
Pets_series = pd.Series(Pets)
Sports_series = pd.Series(Sports)

frame = {'Name': Name_series, 'Height': Height_series, 'Qualifications': Qualifications_series, 'Address': Address_series, 'Age': Age_series, 'Pets': Pets_series, 'Sports': Sports_series}

output = pd.DataFrame(frame)
print(output)

# It was by this point where lots of points covered began clicking. 

Title: studentdata 

      Name  Height Qualifications  Address  Age        Pets          Sports
0      Jai     5.1            Msc    Delhi   21         Dog           Darts
1  Janusha     6.2             MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1            Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2            Msc   Dakhar   21      Parrot         Cricket


### **12. Add a new column to the DataFrame with the following deserts:**

In [45]:
Name = ['Jai', 'Janusha', 'Gaurav', 'Anuj']
Height = [5.1, 6.2, 5.1, 5.2]
Qualifications = ['Msc', 'MA', 'Msc', 'Msc']
Address = ['Delhi', 'Doha', 'Chennai', 'Dakhar']
Age = [21, 23, 24, 21]
Pets = ['Dog', 'Bunny', 'Chinchilla', 'Parrot']
Sports = ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
Desserts = ["Ice Cream", "Cashew Fudge", "Waffels", "Carrot Halwa"]

Name_series = pd.Series(Name)
Height_series = pd.Series(Height)
Qualifications_series = pd.Series(Qualifications)
Address_series = pd.Series(Address)
Age_series = pd.Series(Age)
Pets_series = pd.Series(Pets)
Sports_series = pd.Series(Sports)
Desserts_series = pd.Series(Desserts)

frame = {'Name': Name_series, 'Height': Height_series, 'Qualifications': Qualifications_series, 'Address': Address_series, 'Age': Age_series, 'Pets': Pets_series, 'Sports': Sports_series, 'Desserts': Desserts_series}

output = pd.DataFrame(frame)
print(output)

      Name  Height Qualifications  Address  Age        Pets          Sports  \
0      Jai     5.1            Msc    Delhi   21         Dog           Darts   
1  Janusha     6.2             MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1            Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2            Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     Ice Cream  
1  Cashew Fudge  
2       Waffels  
3  Carrot Halwa  


### **13. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"**

In [87]:
Name = ['Jai', 'Janusha', 'Gaurav', 'Anuj']
Height = [5.1, 6.2, 5.1, 5.2]
Qualifications = ['Msc', 'MA', 'Msc', 'Msc']
Address = ['Delhi', 'Doha', 'Chennai', 'Dakhar']
Age = [21, 23, 24, 21]
Pets = ['Dog', 'Bunny', 'Chinchilla', 'Parrot']
Sports = ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
Desserts = ["Ice Cream", "Cashew Fudge", "Waffels", "Carrot Halwa"]

Name_series = pd.Series(Name)
Height_series = pd.Series(Height)
Qualifications_series = pd.Series(Qualifications)
Address_series = pd.Series(Address)
Age_series = pd.Series(Age)
Pets_series = pd.Series(Pets)
Sports_series = pd.Series(Sports)
Desserts_series = pd.Series(Desserts)

frame = {'Name': Name_series, 'Height': Height_series, 'Qualifications': Qualifications_series, 'Address': Address_series, 'Age': Age_series, 'Pets': Pets_series, 'Sports': Sports_series, 'Desserts': Desserts_series}

studentdata = pd.DataFrame(frame)

studentdata.sort_values(by = ['Name', 'Address'], inplace=True)
print(studentdata)

      Name  Height Qualifications  Address  Age        Pets          Sports  \
3     Anuj     5.2            Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1            Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1            Msc    Delhi   21         Dog           Darts   
1  Janusha     6.2             MA     Doha   23       Bunny      Basketball   

       Desserts  
3  Carrot Halwa  
2       Waffels  
0     Ice Cream  
1  Cashew Fudge  


### **14. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:python df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])**

In [90]:
import pandas as pd

studentdata.to_csv('cows_and_goats.csv')
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
print(df)

        Cows  Goats
Year 1    12     22
Year 2    20     19


### **15. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.**

In [78]:
# A
import pandas as pd

veggies = pd.DataFrame([['Carrots', 'orange'], ['Brocolli', 'green']],
    columns = ['Vegetable', 'Color']) 


veggies.to_csv('veggies.csv')
print(veggies)

  Vegetable   Color
0   Carrots  orange
1  Brocolli   green


In [84]:
#B
import pandas as pd

veggies2 = pd.DataFrame([['Carrots', 'orange', 'chopped'], ['Brocolli', 'green', 'steamed']],
    columns = ['Vegetable', 'Color', 'Cooked']) 

veggies2.to_csv('veggies2_csv')
print(veggies2)

  Vegetable   Color   Cooked
0   Carrots  orange  chopped
1  Brocolli   green  steamed
